name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - name: Build mruby
        run: bin/build clean all
      - name: Run rake
        run: rake
